name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
      
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Đăng nhập Docker Hub trên server (nếu cần, thường chỉ cần lần đầu)
            # echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            # Kéo image mới nhất
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            
            # Dừng và xóa container cũ (nếu đang chạy)
            docker stop frontend || true
            docker rm frontend || true
            
            # Chạy container mới từ image mới nhất
            # Không cần publish port (-p) vì Cloudflare Tunnel sẽ xử lý
            docker run -d \
              --name frontend \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            
            # Dọn dẹp images cũ không dùng đến
            docker image prune -af 